language: node_js
node_js: stable

install: npm install
script: npm run build

notifications:
  email: false

deploy:
  provider: pages
  skip_cleanup: true
  local-dir: dist
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: gh-pages